!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Context

Person(Buyer, "Покупатель", "Пользователь, зарегистрированный в системе, способный совершать покупки")

Person(Seller, "Продавец", "Пользователь, зарегистрированный в системе, способный добавлять и редактировать товары")

Person(Administrator, "Администратор", "Управление учетными записями, формирование отчетов, решение жалоб и возвратов")

Person(System_administrator, "Системный администратор", "Безопасность системы, бэкапы, настройки")

System(App, "Интегрированная система электронной коммерции [Программная система]", "Платформа для поиска, фильтрации и получения рекомендаций товаров с безопасностью покупок и легкостью управления для продавцов")

System_Ext(Delivery, "Служба доставки", "Курьерская служба доставки товаров покупателю")

System_Ext(PaymentSystem, "Банковская система", "Приём денежных средств с учётом налогов и таможенных сборов при международных продажах")


Rel(Buyer, App, "Фильтрация и покупка товаров, оставление отзывов")
Rel(Seller, App, "Добавление и редактирование товаров")
Rel(Administrator, App, "Модерация аккаунтов и жалоб")
Rel(System_administrator, App, "Следит за целостностью системы и безопасностью данных в ней")

Rel(App, Delivery, "Доставка заказанных пользователями товаров в пункты выдачи")
Rel(App, PaymentSystem, "Переводит денежные средства клиентов")